version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mirim_pay_server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
